import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Layout from "./layout";
import Head from 'next/head';

export default function App({ Component, pageProps }: AppProps) {
    return (
      <>
      <Head>
        <title>
        Wikirocket
        </title>
        <meta
          name="Generated by create next app"
        />
      </Head>
      <Layout>
        <Component {...pageProps} />;
      </Layout>
      </>
    );
}
